package au.com.benji.robert.repository

import au.com.benji.robert.models.GlossaryCategory
import au.com.benji.robert.models.GlossaryItem

class GlossaryRepository {
    private val glossaryItems = listOf(
        // Common / Most Used
        GlossaryItem("73", "Best regards", GlossaryCategory.NUMERIC_CODE, true),
        GlossaryItem("88", "Love and kisses", GlossaryCategory.NUMERIC_CODE, true),
        GlossaryItem("QSL", "I acknowledge receipt / Confirming a contact", GlossaryCategory.Q_CODE, true),
        GlossaryItem("QTH", "My location is...", GlossaryCategory.Q_CODE, true),
        GlossaryItem("QRZ", "Who is calling me?", GlossaryCategory.Q_CODE, true),
        GlossaryItem("CQ", "Calling any station (General call)", GlossaryCategory.JARGON, true),
        GlossaryItem("44", "POTA greeting: Nature's best to you (Peace & Harmony)", GlossaryCategory.NUMERIC_CODE, true),
        GlossaryItem("72", "Peace and prosperity (often used by QRP operators)", GlossaryCategory.NUMERIC_CODE, true),

        // Q Codes
        GlossaryItem("QRA", "What is the name of your station?", GlossaryCategory.Q_CODE),
        GlossaryItem("QRG", "Will you tell me my exact frequency?", GlossaryCategory.Q_CODE),
        GlossaryItem("QRH", "Does my frequency vary?", GlossaryCategory.Q_CODE),
        GlossaryItem("QRI", "How is the tone of my transmission?", GlossaryCategory.Q_CODE),
        GlossaryItem("QRK", "What is the readability of my signals?", GlossaryCategory.Q_CODE),
        GlossaryItem("QRL", "Are you busy? / I am busy", GlossaryCategory.Q_CODE),
        GlossaryItem("QRM", "Is my transmission being interfered with? / Interference from other stations", GlossaryCategory.Q_CODE),
        GlossaryItem("QRN", "Are you troubled by static? / Static or atmospheric noise", GlossaryCategory.Q_CODE),
        GlossaryItem("QRO", "Shall I increase transmitter power? / High power", GlossaryCategory.Q_CODE),
        GlossaryItem("QRP", "Shall I decrease transmitter power? / Low power", GlossaryCategory.Q_CODE),
        GlossaryItem("QRQ", "Shall I send faster?", GlossaryCategory.Q_CODE),
        GlossaryItem("QRS", "Shall I send slower?", GlossaryCategory.Q_CODE),
        GlossaryItem("QRT", "Shall I stop sending? / I am closing my station", GlossaryCategory.Q_CODE),
        GlossaryItem("QRU", "Have you anything for me? / I have nothing for you", GlossaryCategory.Q_CODE),
        GlossaryItem("QRV", "Are you ready? / I am ready", GlossaryCategory.Q_CODE),
        GlossaryItem("QRW", "Shall I inform ... that you are calling him?", GlossaryCategory.Q_CODE),
        GlossaryItem("QRX", "When will you call me again? / Standby", GlossaryCategory.Q_CODE),
        GlossaryItem("QRY", "What is my turn?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSA", "What is the strength of my signals?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSB", "Are my signals fading?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSD", "Is my keying defective?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSG", "Shall I send ... messages at a time?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSK", "Can you hear me between your signals?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSL", "Can you acknowledge receipt?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSM", "Shall I repeat the last message I sent?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSN", "Did you hear me on ... kHz?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSO", "Can you communicate with ... direct?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSP", "Will you relay to ...?", GlossaryCategory.Q_CODE),
        GlossaryItem("QST", "General call preceding a message addressed to all amateurs", GlossaryCategory.Q_CODE),
        GlossaryItem("QSU", "Shall I send or reply on this frequency?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSV", "Shall I send a series of V's on this frequency?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSW", "Will you send on this frequency?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSX", "Will you listen to ... on ... kHz?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSY", "Shall I change to transmission on another frequency?", GlossaryCategory.Q_CODE),
        GlossaryItem("QSZ", "Shall I send each word or group more than once?", GlossaryCategory.Q_CODE),
        GlossaryItem("QTA", "Shall I cancel message number ...?", GlossaryCategory.Q_CODE),
        GlossaryItem("QTB", "Do you agree with my counting of words?", GlossaryCategory.Q_CODE),
        GlossaryItem("QTC", "How many messages have you to send?", GlossaryCategory.Q_CODE),
        GlossaryItem("QTH", "What is your location?", GlossaryCategory.Q_CODE),
        GlossaryItem("QTR", "What is the correct time?", GlossaryCategory.Q_CODE),
        GlossaryItem("QTU", "What are the hours during which your station is open?", GlossaryCategory.Q_CODE),
        GlossaryItem("QTX", "Will you keep your station open for further communication with me?", GlossaryCategory.Q_CODE),
        GlossaryItem("QUA", "Have you news of ...?", GlossaryCategory.Q_CODE),

        // 93 Codes (commonly used in some regions, though less formal than Q codes)
        GlossaryItem("93", "Victory / Used as a sign-off (derived from Thelema, sometimes heard in specific circles)", GlossaryCategory.NUMERIC_CODE),

        // Radio Jargon / Terms
        GlossaryItem("Alpha", "A (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Bravo", "B (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Charlie", "C (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Delta", "D (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Echo", "E (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Foxtrot", "F (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Golf", "G (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Hotel", "H (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("India", "I (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Juliet", "J (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Kilo", "K (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Lima", "L (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Mike", "M (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("November", "N (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Oscar", "O (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Papa", "P (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Quebec", "Q (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Romeo", "R (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Sierra", "S (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Tango", "T (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Uniform", "U (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Victor", "V (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Whiskey", "W (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("X-ray", "X (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Yankee", "Y (Phonetic)", GlossaryCategory.PHONETIC),
        GlossaryItem("Zulu", "Z (Phonetic) / UTC time", GlossaryCategory.PHONETIC),
        
        GlossaryItem("DX", "Distance / Long distance contact", GlossaryCategory.JARGON),
        GlossaryItem("ELMER", "An experienced ham who mentors others", GlossaryCategory.JARGON),
        GlossaryItem("FB", "Fine Business (Good job / nice)", GlossaryCategory.JARGON),
        GlossaryItem("HI HI", "Laughter on CW (sounds like hi hi)", GlossaryCategory.JARGON),
        GlossaryItem("OM", "Old Man (Any male amateur)", GlossaryCategory.JARGON),
        GlossaryItem("XYL", "Ex-Young Lady (Wife)", GlossaryCategory.JARGON),
        GlossaryItem("YL", "Young Lady (Any female amateur)", GlossaryCategory.JARGON),
        GlossaryItem("RST", "Readability, Strength, Tone (Signal report)", GlossaryCategory.JARGON),
        GlossaryItem("RIG", "The radio transmitter/receiver", GlossaryCategory.JARGON),
        GlossaryItem("SHACK", "The room where the radio equipment is located", GlossaryCategory.JARGON),
        GlossaryItem("WORKED", "Made contact with another station", GlossaryCategory.JARGON),
        GlossaryItem("BOOTLEGGER", "Unlicensed person operating on ham bands", GlossaryCategory.JARGON),
        GlossaryItem("PILEUP", "Many stations calling a single DX station at once", GlossaryCategory.JARGON),
        GlossaryItem("RIT", "Receiver Incremental Tuning", GlossaryCategory.JARGON),
        GlossaryItem("SPLIT", "Operating on one frequency and listening on another", GlossaryCategory.JARGON),
        GlossaryItem("TRAFFIC", "Messages sent over the air", GlossaryCategory.JARGON),
        GlossaryItem("WARC", "World Administrative Radio Conference (Refers to 30m, 17m, 12m bands)", GlossaryCategory.JARGON),
        GlossaryItem("ZULU", "Coordinated Universal Time (UTC)", GlossaryCategory.JARGON)
    )

    fun getGlossaryItems() = glossaryItems
}
